Visitar link: 

https://www.youtube.com/watch?v=33KWtdO8uoU&t=212s&ab_channel=AprendeIAconLigdiGonzalez

https://www.aprendemachinelearning.com/random-forest-el-poder-del-ensamble/

## Sistema de predicción de la temperatura

El siguiente código de Python se carga en los datos csv y muestra la estructura de los datos:

In [1]:
import pandas as pd
dataset = pd.read_csv('temps.csv') 
dataset.head(5)
#https://www.kaggle.com/ns0720/tempscsv

year  month  day  week  temp_2  temp_1  average  actual  friend
0  2019      1    1   Fri      45      45     45.6      45      29
1  2019      1    2   Sat      44      45     45.7      44      61
2  2019      1    3   Sun      45      44     45.8      41      56
3  2019      1    4   Mon      44      41     45.9      40      53
4  2019      1    5  Tues      41      40     46.0      44      41

In [2]:
dataset.describe()

year       month         day  ...     average      actual      friend
count   348.0  348.000000  348.000000  ...  348.000000  348.000000  348.000000
mean   2019.0    6.477011   15.514368  ...   59.760632   62.543103   60.034483
std       0.0    3.498380    8.772982  ...   10.527306   11.794146   15.626179
min    2019.0    1.000000    1.000000  ...   45.100000   35.000000   28.000000
25%    2019.0    3.000000    8.000000  ...   49.975000   54.000000   47.750000
50%    2019.0    6.000000   15.000000  ...   58.200000   62.500000   60.000000
75%    2019.0   10.000000   23.000000  ...   69.025000   71.000000   71.000000
max    2019.0   12.000000   31.000000  ...   77.400000   92.000000   95.000000

[8 rows x 8 columns]

In [3]:
dataset.shape

(348, 9)

In [4]:
#Codificar los datos usando pandas get_dummies
dataset = pd.get_dummies(dataset)
# Mostrar las primeras 5 filas de las últimas 12 columnas
dataset.iloc[:,5:].head(5)

average  actual  friend  week_Fri  ...  week_Sun  week_Thurs  week_Tues  week_Wed
0     45.6      45      29         1  ...         0           0          0         0
1     45.7      44      61         0  ...         0           0          0         0
2     45.8      41      56         0  ...         1           0          0         0
3     45.9      40      53         0  ...         0           0          0         0
4     46.0      44      41         0  ...         0           0          1         0

[5 rows x 10 columns]

In [5]:
# Utilice numpy para convertir a matrices
import numpy as np
# Las etiquetas son los valores que queremos predecir
labels = np.array(dataset['actual'])
labels

array([45, 44, 41, 40, 44, 51, 45, 48, 50, 52, 45, 49, 55, 49, 48, 54, 50,
       54, 48, 52, 52, 57, 48, 51, 54, 56, 57, 56, 52, 48, 47, 46, 51, 49,
       49, 53, 49, 51, 57, 62, 56, 55, 58, 55, 56, 57, 53, 51, 53, 51, 51,
       60, 59, 61, 60, 57, 53, 58, 55, 59, 57, 64, 60, 53, 54, 55, 56, 55,
       52, 54, 49, 51, 53, 58, 63, 61, 55, 56, 57, 53, 54, 57, 59, 51, 56,
       64, 68, 73, 71, 63, 69, 60, 57, 68, 77, 76, 66, 59, 58, 60, 59, 59,
       60, 68, 77, 89, 81, 81, 73, 64, 65, 55, 59, 60, 61, 64, 61, 68, 77,
       87, 74, 60, 68, 77, 82, 63, 67, 75, 81, 77, 82, 65, 57, 60, 71, 64,
       63, 66, 59, 66, 65, 66, 66, 65, 64, 64, 64, 71, 79, 75, 71, 80, 81,
       92, 86, 85, 67, 65, 67, 65, 70, 66, 60, 67, 71, 67, 65, 70, 76, 73,
       75, 68, 69, 71, 78, 85, 79, 74, 73, 76, 76, 71, 68, 69, 76, 68, 74,
       71, 74, 74, 77, 75, 77, 76, 72, 80, 73, 78, 82, 81, 71, 75, 80, 85,
       79, 83, 85, 88, 76, 73, 77, 73, 75, 80, 79, 72, 72, 73, 72, 76, 80,
       87, 90, 83, 84, 81

In [6]:
#Quitar las etiquetas
dataset= dataset.drop('actual', axis = 1)
#Guardar nombres de las columbas uso posterior
dataset_list = list(dataset.columns)
# Convertir a array numpy
dataset = np.array(dataset)
dataset

array([[2.019e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 1.000e+00, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 1.000e+00, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.019e+03, 1.200e+01, 2.900e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 1.200e+01, 3.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 1.200e+01, 3.100e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [7]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(dataset, labels, test_size = 0.25, 
                                                                            random_state = 42)
train_features

array([[2.019e+03, 9.000e+00, 1.900e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 4.000e+00, 1.400e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 7.000e+00, 3.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.019e+03, 4.000e+00, 1.900e+01, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.019e+03, 1.000e+01, 1.400e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 4.000e+00, 1.500e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [8]:
test_features

array([[2.019e+03, 9.000e+00, 2.900e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 4.000e+00, 2.700e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.019e+03, 1.100e+01, 2.800e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.019e+03, 1.000e+01, 5.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.019e+03, 3.000e+00, 4.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.019e+03, 1.200e+01, 2.200e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00]])

In [9]:
train_labels

array([71, 59, 76, 57, 54, 54, 52, 82, 35, 41, 48, 80, 68, 39, 85, 79, 52,
       76, 53, 41, 48, 61, 77, 68, 46, 43, 71, 62, 67, 74, 57, 52, 59, 54,
       47, 55, 66, 54, 40, 45, 67, 70, 45, 65, 67, 57, 61, 72, 76, 55, 67,
       73, 57, 54, 75, 66, 65, 60, 59, 58, 52, 51, 51, 64, 68, 55, 62, 44,
       63, 64, 40, 68, 71, 76, 65, 71, 57, 35, 75, 71, 75, 77, 57, 49, 90,
       68, 59, 87, 68, 68, 40, 46, 64, 52, 71, 79, 68, 86, 72, 41, 64, 58,
       67, 74, 59, 73, 55, 75, 63, 58, 48, 51, 65, 81, 80, 73, 60, 76, 69,
       56, 46, 55, 57, 64, 74, 49, 65, 55, 53, 52, 75, 66, 68, 65, 83, 60,
       76, 62, 73, 79, 77, 55, 63, 60, 85, 63, 57, 42, 66, 65, 44, 45, 53,
       59, 52, 59, 79, 77, 55, 72, 80, 68, 68, 58, 49, 72, 64, 71, 67, 51,
       51, 71, 52, 56, 61, 68, 63, 60, 63, 59, 60, 64, 81, 50, 54, 48, 67,
       56, 49, 60, 72, 50, 77, 88, 75, 46, 76, 40, 50, 60, 75, 66, 55, 73,
       77, 61, 89, 61, 44, 51, 54, 83, 49, 64, 60, 59, 68, 71, 49, 71, 60,
       65, 42, 71, 55, 39

In [10]:
test_labels

array([66, 61, 52, 66, 70, 82, 85, 84, 65, 92, 61, 85, 44, 65, 69, 62, 64,
       56, 53, 79, 63, 57, 67, 62, 59, 56, 65, 52, 66, 76, 64, 61, 48, 81,
       77, 57, 58, 47, 68, 51, 77, 56, 73, 51, 59, 87, 58, 81, 58, 42, 49,
       40, 65, 64, 70, 65, 53, 57, 53, 60, 67, 49, 53, 69, 55, 68, 76, 69,
       78, 36, 74, 57, 69, 50, 56, 67, 48, 80, 48, 49, 57, 77, 81, 67, 66,
       57, 45])

In [11]:
train_features.shape

(261, 14)

In [12]:
train_labels.shape

(261,)

In [13]:
test_features.shape

(87, 14)

In [14]:
test_labels.shape

(87,)

# Entrenamos el modelo

In [15]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(train_features, train_labels);

# Hacemos las predicciones sobre la data de test

In [16]:
predictions = rf.predict(test_features)
errors = abs(predictions - test_labels)
mape = 100 * (errors / test_labels)
accuracy = 100 - np.mean(mape)
round(accuracy, 2)

93.98

Esto es bueno, el algoritmo ha aprendido a predecir la temperatura para el día siguiente con una precisión del 94%.

No habíamos visto como graficar el árbol, observe el siguiente código y su resultado en la carpeta de los archivos.

In [17]:
from sklearn.tree import export_graphviz
import pydot
tree = rf.estimators_[5]
from sklearn.tree import export_graphviz
import pydot
tree = rf.estimators_[5]
export_graphviz(tree, out_file = 'tree.dot', feature_names = dataset_list, rounded = True, precision = 1)
(graph, ) = pydot.graph_from_dot_file('tree.dot')
graph.write_png('tree.png')