In [1]:
import numpy as np

#Array de una dimencion
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
#array de 2 dimenciones
b = np.array([(1,2,3,0),(4,5,6,1),(7,8,9,2)])
print(b)

[[1 2 3 0]
 [4 5 6 1]
 [7 8 9 2]]


In [3]:
#crear matrizes con 0
ceros = np.zeros((4,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
#crear matriz vacia
vacia = np.empty((5,5))
print(vacia)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.33645148e-307
  1.89146896e-307]
 [7.56571288e-307 3.11525958e-307 1.24610723e-306 1.37962320e-306
  1.29060871e-306]
 [2.22518251e-306 1.33511969e-306 1.78022342e-306 1.05700345e-307
  1.11261027e-306]
 [1.11261502e-306 1.42410839e-306 7.56597770e-307 6.23059726e-307
  1.42419530e-306]
 [7.56599128e-307 1.78022206e-306 8.34451503e-308 2.22507386e-306
  2.56761491e-312]]


In [5]:
#crear una matriz con valor fijo
full = np.full((5,5),2)
print(full)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [6]:
#matriz identidad
identidad = np.eye(4,4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#crear arrray con valores espaciados unidormemente
espacio = np.arange(0,50,5)
print(espacio)
espacio1 = np.arange(start=100, stop=1, step=5)
print(espacio1)

espacio2 = np.linspace(2,10,5)
print(espacio2)

[ 0  5 10 15 20 25 30 35 40 45]
[]
[ 2.  4.  6.  8. 10.]


In [8]:
#imprimir las dimenciones de una matriz
print(b.ndim)

2


In [9]:
#el tipo de datos de la matriz
print(full.dtype)

int32


In [10]:
#cambiar la forma de la matriz
m1 = np.array([(1,2,3),(4,5,6)])
print(m1)

m2 = m1.reshape(3,2)
print(m2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [11]:
#imprimir una columna de la matriz
print(m2[:0])

[]


In [12]:
#imprimir una celda
print(b[1,1])

5


In [13]:
#el valor minimo
print(b.min())

0


In [14]:
#el valor maximo 
print(b.max)

<built-in method max of numpy.ndarray object at 0x0000022C187A4ED0>


In [15]:
#suma de los valores
print(b.sum())

48


In [16]:
notas = np.array([(4.5,3.5,2.0),(4.0,5.0,3.5),(4.5,3.5,2.0)])
print(notas)
print(np.std(notas))

[[4.5 3.5 2. ]
 [4.  5.  3.5]
 [4.5 3.5 2. ]]
0.9938079899999066


In [17]:
#operaciones con matrices
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
y = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
