In [2]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [12]:
x, y = load_digits(return_X_y=True)
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [13]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [15]:
regression = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
regression.fit(x_train, y_train)
print(regression.classes_)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
x_test = scaler.fit_transform(x_test)
y_pred = regression.predict(x_test)
y_pred

array([1, 2, 5, 9, 4, 3, 3, 6, 9, 1, 9, 6, 3, 2, 8, 0, 6, 6, 3, 8, 2, 1,
       6, 2, 9, 2, 4, 1, 0, 3, 9, 5, 0, 4, 2, 1, 6, 0, 9, 9, 2, 4, 0, 4,
       9, 5, 7, 9, 6, 8, 0, 3, 4, 3, 4, 2, 5, 3, 8, 8, 6, 4, 1, 2, 3, 0,
       8, 5, 6, 3, 5, 0, 4, 6, 5, 1, 3, 9, 2, 4, 7, 1, 2, 3, 5, 5, 3, 5,
       3, 8, 9, 9, 7, 7, 3, 4, 5, 9, 2, 9, 2, 2, 8, 8, 2, 2, 6, 8, 8, 3,
       6, 9, 4, 2, 6, 6, 0, 3, 3, 3, 8, 5, 4, 0, 0, 8, 9, 6, 4, 6, 1, 7,
       6, 5, 0, 4, 0, 0, 1, 6, 1, 4, 4, 7, 2, 2, 5, 3, 3, 1, 0, 4, 4, 4,
       4, 6, 0, 9, 1, 2, 3, 0, 8, 1, 2, 7, 0, 0, 0, 2, 6, 9, 7, 1, 6, 3,
       6, 5, 1, 7, 5, 7, 7, 6, 3, 5, 4, 1, 5, 1, 7, 3, 0, 7, 1, 7, 1, 7,
       7, 7, 5, 8, 9, 1, 6, 0, 4, 9, 2, 5, 2, 4, 1, 3, 7, 5, 1, 2, 7, 1,
       6, 4, 0, 2, 1, 9, 9, 6, 8, 6, 8, 9, 7, 6, 8, 4, 7, 8, 0, 3, 1, 3,
       3, 8, 6, 2, 0, 4, 8, 6, 3, 4, 5, 1, 0, 0, 8, 3, 3, 2, 9, 0, 0, 5,
       4, 5, 7, 2, 7, 9, 4, 5, 2, 4, 7, 8, 7, 1, 7, 2, 8, 8, 7, 3, 8, 5,
       0, 3, 5, 6, 2, 9, 0, 1, 3, 1, 4, 6, 1, 5, 8,

In [17]:
regression.score(x_test,y_test)

0.9638888888888889