Importar numpy

In [ ]:
import numpy as np

Arreglos (arrays)

In [ ]:
arr1 = [[1,2,3],
 [4,5,6],
 [7,8,9],
 [10,11,12]]

In [ ]:
#Sacamos copia del arr1
arr2 = np.array(arr1)
#imprimimos la columna 0
arr2[:, 0]

array([ 1,  4,  7, 10])

Tipos de datos en numpy

In [ ]:
arr3 = arr2.astype(np.int32)

In [ ]:
arr3.dtype

dtype('int32')

In [ ]:
arr3[0, 0] = 1000

In [ ]:
arr3

array([[1000,    2,    3],
       [   4,    5,    6],
       [   7,    8,    9],
       [  10,   11,   12]], dtype=int32)

In [ ]:
arr4 = np.array([1.3,3.4,5.3])
arr4.astype(np.float32)

array([1.3, 3.4, 5.3], dtype=float32)

In [ ]:
arr4.astype(np.int64)

array([1, 3, 5])

In [ ]:
arr5 = np.array(['a', 'b', 'c'])
arr5.dtype

dtype('<U1')

shape

In [ ]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr2.shape

(4, 3)

reshape

In [ ]:
arr2.reshape((2,-1,6))

array([[[ 1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12]]])

astype

# creando arrays

zeros

In [ ]:
arr6 = np.zeros((4,5),dtype=int)

ones

In [ ]:
np.ones((2,15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

full

In [ ]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

eyes

In [ ]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

arange

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

linspace

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

diag

In [ ]:
np.diag([1,3,4,6,7,8])

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 8]])

random

In [ ]:
np.random.random([4,3])

array([[0.3633302 , 0.96863149, 0.63704641],
       [0.33937155, 0.96216899, 0.14539585],
       [0.66542509, 0.86946027, 0.99189192],
       [0.182281  , 0.10022973, 0.67239627]])

randint

In [ ]:
np.random.randint(4, 9, [3,4])

array([[8, 7, 7, 6],
       [5, 7, 7, 6],
       [8, 8, 7, 8]])

# Indexing

In [ ]:
arr6 = np.random.randint(0, 100, [6, 7])

In [ ]:
arr6

array([[ 4, 34, 28, 74, 62,  8,  0],
       [20, 92, 63, 56, 65, 29, 81],
       [60, 56, 92, 24, 37, 32, 92],
       [54, 48, 37, 65, 94, 21, 84],
       [82, 37,  6, 49, 86, 17, 70],
       [99, 37, 16, 16, 41, 13, 70]])

Indices

In [ ]:
arr6[0,0]

4

In [ ]:
arr6[3, :]

array([54, 48, 37, 65, 94, 21, 84])

In [ ]:
arr6[3, ::2]

array([54, 37, 94, 84])

In [ ]:
arr6[:, 4]

array([62, 65, 37, 94, 86, 41])

In [ ]:
arr6[2::-1, 4]

array([37, 65, 62])

In [ ]:
arr6

array([[ 4, 34, 28, 74, 62,  8,  0],
       [20, 92, 63, 56, 65, 29, 81],
       [60, 56, 92, 24, 37, 32, 92],
       [54, 48, 37, 65, 94, 21, 84],
       [82, 37,  6, 49, 86, 17, 70],
       [99, 37, 16, 16, 41, 13, 70]])

In [ ]:
arr6[2:4, 2:4]

array([[92, 24],
       [37, 65]])

Listas de indices

In [ ]:
arr6

array([[ 4, 34, 28, 74, 62,  8,  0],
       [20, 92, 63, 56, 65, 29, 81],
       [60, 56, 92, 24, 37, 32, 92],
       [54, 48, 37, 65, 94, 21, 84],
       [82, 37,  6, 49, 86, 17, 70],
       [99, 37, 16, 16, 41, 13, 70]])

In [ ]:
arr6[[0,-1], :]

array([[ 4, 34, 28, 74, 62,  8,  0],
       [99, 37, 16, 16, 41, 13, 70]])

Listas de bools

In [ ]:
arr6[:, [True, True, True, True, True, False, False]]

array([[ 4, 34, 28, 74, 62],
       [20, 92, 63, 56, 65],
       [60, 56, 92, 24, 37],
       [54, 48, 37, 65, 94],
       [82, 37,  6, 49, 86],
       [99, 37, 16, 16, 41]])

In [ ]:
arr6

array([[ 4, 34, 28, 74, 62,  8,  0],
       [20, 92, 63, 56, 65, 29, 81],
       [60, 56, 92, 24, 37, 32, 92],
       [54, 48, 37, 65, 94, 21, 84],
       [82, 37,  6, 49, 86, 17, 70],
       [99, 37, 16, 16, 41, 13, 70]])

In [ ]:
arr6[:2, :2] = np.array([[1,1], [1,1]])

In [ ]:
arr6

array([[ 1,  1, 28, 97, 99, 13,  4],
       [ 1,  1, 27, 32, 64, 95, 68],
       [37, 18,  6, 89, 72, 10, 50],
       [32, 10, 68, 36, 32, 81, 51],
       [39, 45,  9, 65, 64,  2, 59],
       [50,  2,  5, 58, 11, 41, 77]])

# Concatenación

In [ ]:
arr7 = np.random.randint(0,100, (4,5))

In [ ]:
arr7

array([[ 1, 88, 82, 38, 44],
       [49, 34, 22, 41, 23],
       [14, 96, 51, 93, 72],
       [ 6, 31, 35, 94, 86]])

filas

In [ ]:
np.vstack([
    np.ones((2,5)),
    arr7,
])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1., 88., 82., 38., 44.],
       [49., 34., 22., 41., 23.],
       [14., 96., 51., 93., 72.],
       [ 6., 31., 35., 94., 86.]])

columnas

In [ ]:
arr7

array([[ 1, 88, 82, 38, 44],
       [49, 34, 22, 41, 23],
       [14, 96, 51, 93, 72],
       [ 6, 31, 35, 94, 86]])

In [ ]:
np.hstack([
    np.full((4, 2), 10),
    arr7
])

array([[10, 10,  1, 88, 82, 38, 44],
       [10, 10, 49, 34, 22, 41, 23],
       [10, 10, 14, 96, 51, 93, 72],
       [10, 10,  6, 31, 35, 94, 86]])

# Comparaciones

Operadores de comparación

In [ ]:
arr7

array([[ 1, 88, 82, 38, 44],
       [49, 34, 22, 41, 23],
       [14, 96, 51, 93, 72],
       [ 6, 31, 35, 94, 86]])

In [ ]:
arr7 < 50

array([[ True, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [ True,  True,  True, False, False]])

In [ ]:
arr7[:, arr7[0,:] > 40]

array([[88, 82, 44],
       [34, 22, 23],
       [96, 51, 72],
       [31, 35, 86]])

In [ ]:
arr7[:, 0] > 60

array([False, False, False, False])

In [ ]:
arr8 = np.array([['hola', 2], ['chao', 4]])

In [ ]:
arr8

array([['hola', '2'],
       ['chao', '4']], dtype='<U4')

In [ ]:
arr8[arr8[:, 0] == 'chao']

array([['chao', '4']], dtype='<U4')

# Operaciones aritméticas

In [ ]:
ar1 = np.random.randint(0,100,(3,4))
ar2 = np.random.randint(0,100,(3,4))

In [ ]:
print(ar1)
ar2

[[13 53 74 49]
 [65 13 59 79]
 [23 67 49 15]]


array([[84, 73, 82, 85],
       [51, 41, 13, 92],
       [87, 94, 75, 34]])

suma

In [ ]:
ar1 + ar2

array([[ 97, 126, 156, 134],
       [116,  54,  72, 171],
       [110, 161, 124,  49]])

resta

In [ ]:
ar1 - ar2

array([[-71, -20,  -8, -36],
       [ 14, -28,  46, -13],
       [-64, -27, -26, -19]])

multiplicación

In [ ]:
ar1 * ar2

array([[1092, 3869, 6068, 4165],
       [3315,  533,  767, 7268],
       [2001, 6298, 3675,  510]])

producto punto

In [ ]:
ar1

array([[13, 53, 74, 49],
       [65, 13, 59, 79],
       [23, 67, 49, 15]])

In [ ]:
ar2

array([[84, 73, 82, 85],
       [51, 41, 13, 92],
       [87, 94, 75, 34]])

In [ ]:
ar2.reshape((4,3))

array([[84, 73, 82],
       [85, 51, 41],
       [13, 92, 87],
       [94, 75, 34]])

In [ ]:
ar1 @ ar2.reshape((4,3)) # != ar2 @ ar1

array([[11165, 14135, 11343],
       [14758, 16761, 13682],
       [ 9674, 10729,  9406]])

división

In [ ]:
ar1 / ar2

array([[0.1547619 , 0.7260274 , 0.90243902, 0.57647059],
       [1.2745098 , 0.31707317, 4.53846154, 0.85869565],
       [0.26436782, 0.71276596, 0.65333333, 0.44117647]])

exponente

In [ ]:
ar1 ** ar2

array([[ 4232974902558095569, -5116654396780829675,                    0,
         6880905010996113905],
       [-1244751537030054719,   660746719859712045, -7772847348627950677,
        -1245784131012530879],
       [  837559365727783143,  7442686547985349689, -8663673126898889455,
         5676732407545605857]])

# Funciones útiles

max

In [ ]:
arr7

array([[ 1, 88, 82, 38, 44],
       [49, 34, 22, 41, 23],
       [14, 96, 51, 93, 72],
       [ 6, 31, 35, 94, 86]])

In [ ]:
arr7.max(axis=1)

array([88, 49, 96, 94])

min

mean

In [ ]:
arr7.mean(axis=1)

array([50.6, 33.8, 65.2, 50.4])

median

In [ ]:
np.median(arr7, axis=1)

array([44., 34., 72., 35.])

argmin

In [ ]:
arr7.argmin(axis=0)

array([0, 3, 1, 0, 1])

argmax

sort

In [ ]:
arr7.sort(axis=0)

In [ ]:
arr7

array([[ 1, 31, 22, 38, 23],
       [ 6, 34, 35, 41, 44],
       [14, 88, 51, 93, 72],
       [49, 96, 82, 94, 86]])

trigonométricas

In [ ]:
np.sin(arr7)
# np.cos

array([[ 0.84147098, -0.40403765, -0.00885131,  0.29636858, -0.8462204 ],
       [-0.2794155 ,  0.52908269, -0.42818267, -0.15862267,  0.01770193],
       [ 0.99060736,  0.0353983 ,  0.67022918, -0.94828214,  0.25382336],
       [-0.95375265,  0.98358775,  0.31322878, -0.24525199, -0.92345845]])